export type Price = number | { q?: number; h?: number; f?: number } | "APS";

export interface MenuItem {
  name: string;
  price: Price;
  desc?: string;
  badge?: "Signature" | "Bestseller" | "Popular" | "Must Try" | "Family Favourite";
}

export interface MenuCategory {
  id: string;
  title: string;
  items: MenuItem[];
}

export const SIGNATURE_DISHES: MenuItem[] = [
  { name: "Jallikettu Beef Rib Mandi", price: { q: 350, h: 690, f: 1350 }, desc: "Our signature mandi — tender beef ribs slow-cooked over aromatic basmati rice.", badge: "Signature" },
  { name: "Jalikkettu Beef Rib", price: 310, desc: "Soft, juicy, flavour-packed beef rib prepared with Qawwali's signature spices.", badge: "Bestseller" },
  { name: "Chicken Curry", price: 260, desc: "Classic Kerala-style chicken curry simmered in aromatic spices and coconut.", badge: "Must Try" },
  { name: "Chicken Mandi", price: { q: 220, h: 410, f: 790 }, desc: "Fragrant mandi rice topped with succulent grilled chicken.", badge: "Family Favourite" },
  { name: "Al-Faham Mandi", price: { q: 230, h: 450, f: 890 }, desc: "Charcoal-grilled chicken served on a bed of saffron rice.", badge: "Bestseller" },
  { name: "Shawarma Meal", price: 299, desc: "Turkish-style shawarma with sides — a complete meal.", badge: "Popular" },
  { name: "Non Vegetarian Sadya", price: 599, desc: "Kerala-style feast platter with multiple non-veg specialities." },
  { name: "Arabic Tawa Platter", price: 3000, desc: "The ultimate sharing platter — grilled meats, prawns, kebabs, rice & hummus.", badge: "Signature" },
];

export const MENU: MenuCategory[] = [
  {
    id: "mandi", title: "Qawwali Special Mandi",
    items: [
      { name: "Chicken Mandi", price: { q: 220, h: 410, f: 790 }, badge: "Bestseller" },
      { name: "Al-Faham Mandi", price: { q: 230, h: 450, f: 890 } },
      { name: "Pepper Al-Faham Mandi", price: { q: 230, h: 450, f: 890 } },
      { name: "Peri Peri Al-Faham Mandi", price: { q: 230, h: 450, f: 890 } },
      { name: "Spicy Al-Faham Mandi", price: { q: 230, h: 450, f: 890 } },
      { name: "Cheese Al-Faham Mandi", price: { q: 260, h: 510, f: 990 } },
      { name: "Honey Al-Faham Mandi", price: { q: 240, h: 450, f: 910 } },
      { name: "Jalikkettu Al-Faham Mandi", price: { q: 260, h: 510, f: 990 } },
      { name: "Jalikkettu Chicken Mandi", price: { q: 250, h: 500, f: 980 } },
      { name: "Jalikkettu Beef Rib Mandi", price: { q: 350, h: 690, f: 1350 }, badge: "Signature" },
      { name: "Shuwa Beef Rib Mandi", price: { q: 330, h: 640, f: 1250 } },
      { name: "Fish Mandi Neymeen (Q)", price: 450 },
      { name: "Fish Mandi Hamour & Rice", price: "APS" },
      { name: "Fish Mandi Kalanki 1kg & Rice", price: "APS" },
      { name: "Mandi Rice 500g", price: 80 },
    ],
  },
  {
    id: "alfaham", title: "Al-Faham",
    items: [
      { name: "Al-Faham", price: { q: 170, h: 330, f: 650 }, badge: "Popular" },
      { name: "Peri Peri Al-Faham", price: { q: 180, h: 350, f: 690 } },
      { name: "Pepper Al-Faham", price: { q: 180, h: 350, f: 690 } },
      { name: "Spicy Al-Faham", price: { q: 180, h: 350, f: 690 } },
      { name: "Kanthari Al-Faham", price: { q: 180, h: 350, f: 690 } },
      { name: "Kizhi Al-Faham", price: { q: 250, h: 500, f: 1000 } },
      { name: "Cheese Al-Faham", price: { q: 210, h: 410, f: 810 } },
      { name: "Honey Al-Faham", price: { q: 190, h: 370, f: 720 } },
      { name: "Qawwali Special Jalikkettu", price: { q: 210, h: 410, f: 810 }, badge: "Signature" },
      { name: "Passion Fruit Al-Faham", price: { q: 220, h: 420, f: 820 } },
      { name: "Orange Fruit Al-Faham", price: { q: 190, h: 370, f: 720 } },
      { name: "Afghani Al-Faham", price: { q: 250, h: 480, f: 950 } },
      { name: "Mandi Chicken Pieces", price: { q: 170, h: 340, f: 680 } },
      { name: "Selection Piece", price: 20 },
    ],
  },
  {
    id: "arabic", title: "Arabic Food",
    items: [
      { name: "Chicken Tawa", price: 250 },
      { name: "Chicken Tawa Biryani", price: 330 },
      { name: "Chicken Pepper Tawa", price: 260 },
      { name: "Chicken Pepper Tawa Biryani", price: 340 },
      { name: "Deja Herbs", price: 600 },
      { name: "Benyan Dejaj", price: { h: 400, f: 700 } },
      { name: "Deja Haar", price: { h: 400, f: 720 } },
      { name: "Beef With Hummus", price: 399 },
      { name: "Beef Raan", price: 400 },
      { name: "Beef Raan Biryani", price: 480 },
      { name: "Beef Raan Pepper Tawa", price: 420 },
      { name: "Beef Raan Pepper Biryani", price: 500 },
      { name: "Arabic Fish Tawa Masala", price: "APS" },
      { name: "Arabic Fish Biryani", price: "APS" },
      { name: "Arabic Fish Tawa Fry", price: "APS" },
      { name: "Kanthari Fish Tawa", price: "APS" },
      { name: "Arabic Prawns Tawa", price: "APS" },
      { name: "Tiger Prawns Tawa", price: "APS" },
      { name: "Basha Fish Pepper Tawa", price: "APS" },
      { name: "Basha Fish Kanthari Tawa", price: "APS" },
      { name: "Arabic Tawa Platter", price: 3000, badge: "Signature" },
      { name: "Arabic Couple Tawa Platter", price: 1200 },
      { name: "Arabic Biryani Rice", price: 80 },
    ],
  },
  {
    id: "shawarma", title: "Turkish Chicken Shawarma",
    items: [
      { name: "Turkish Roll", price: 130, badge: "Popular" },
      { name: "Turkish Cheese Roll", price: 150 },
      { name: "Turkish Plate", price: 170 },
      { name: "Turkish Fantasia", price: 220 },
      { name: "Turkish Full Meat Cheese Roll", price: 190 },
      { name: "Turkish Full Meat Roll", price: 170 },
      { name: "Turkish Mathafi", price: 220 },
      { name: "Turkish Sarookh Rocket", price: 190 },
      { name: "Turkish Shawarma Qawwali Special", price: 200, badge: "Signature" },
    ],
  },
  {
    id: "chicken", title: "Chicken",
    items: [
      { name: "Chicken Kanthari", price: 260 },
      { name: "Chicken Kurumulaku Fry", price: 260 },
      { name: "Chicken Neelagiri Kuruma", price: 260 },
      { name: "Chicken Perattu", price: 260 },
      { name: "Chicken Roast", price: 260 },
      { name: "Chicken Ularthi", price: 260 },
      { name: "Ginger Chicken", price: 260 },
      { name: "Japan Chicken", price: 260, badge: "Must Try" },
      { name: "Pepper Chicken", price: 260 },
      { name: "Malabar Chicken Curry", price: 260 },
      { name: "Nadan Chicken Curry", price: 260 },
    ],
  },
  {
    id: "beef", title: "Beef",
    items: [
      { name: "Beef Thengakothu", price: 230 },
      { name: "Beef Ularthu", price: 230 },
      { name: "Beef Varattiyathu", price: 230 },
      { name: "Jalikkettu Beef Rib", price: 310, badge: "Signature" },
      { name: "Beef Rib 300g", price: 230 },
      { name: "Beef Roast", price: 230 },
      { name: "Beef Curry", price: 230 },
      { name: "Beef Fry", price: 230 },
    ],
  },
  {
    id: "seafood", title: "Seafood & Fish",
    items: [
      { name: "Kanthari Tawa Fry", price: 280 },
      { name: "Prawns Fry", price: 380 },
      { name: "Prawns Masala", price: 380 },
      { name: "Prawns Tawa Fry", price: 380 },
      { name: "Prawns Manchurian", price: 380 },
      { name: "Palli Kappa Beef Rib", price: 390 },
      { name: "Alleppey Meen Curry", price: 380 },
      { name: "Fish Chatti Curry", price: 340 },
      { name: "Fish Chatti Tuna", price: 340 },
      { name: "Fish Mango Curry", price: 340 },
      { name: "Fish Molly", price: 340 },
      { name: "Fish Mulakittathu", price: 340 },
      { name: "Fish Pepper", price: 340 },
      { name: "Fish Pollichathu", price: 340 },
      { name: "Fish Roast", price: 340 },
      { name: "Travancore Fish Curry", price: 340 },
      { name: "Trivandrum Fish Curry", price: 340 },
    ],
  },
  {
    id: "chinese", title: "Chinese",
    items: [
      { name: "Fish Manchurian", price: 340 },
      { name: "Fish Manchurian Dry", price: 340 },
      { name: "Chilli Beef", price: 260 },
      { name: "Chilli Beef Dry", price: 260 },
      { name: "Chilli Chicken", price: 260 },
      { name: "Chilli Chicken Dry", price: 260 },
      { name: "Garlic Chicken", price: 260 },
      { name: "Ginger Chicken", price: 260 },
      { name: "Schezwan Chicken", price: 260 },
    ],
  },
  {
    id: "rice-noodles", title: "Rice & Noodles",
    items: [
      { name: "Chicken Fried Rice", price: 190 },
      { name: "Vegetable Fried Rice", price: 150 },
      { name: "Egg Fried Rice", price: 160 },
      { name: "Mandarin Chicken Fried Rice", price: 200 },
      { name: "Mixed Fried Rice", price: 220 },
      { name: "Schezwan Chicken Fried Rice", price: 200 },
      { name: "Schezwan Mixed Fried Rice", price: 240 },
      { name: "Schezwan Vegetable Fried Rice", price: 160 },
      { name: "Schezwan Egg Fried Rice", price: 170 },
      { name: "Singapore Vegetable Fried Rice", price: 160 },
      { name: "Chicken Noodles", price: 190 },
      { name: "Chopsuey Qawwali", price: 250, badge: "Signature" },
      { name: "Egg Noodles", price: 160 },
      { name: "Mixed Noodles", price: 220 },
      { name: "Singapore Vegetable Noodles", price: 160 },
      { name: "Vegetable Noodles", price: 150 },
      { name: "Schezwan Egg Noodles", price: 170 },
      { name: "Schezwan Chicken Noodles", price: 200 },
    ],
  },
  {
    id: "north-indian", title: "North Indian",
    items: [
      { name: "Butter Chicken Masala", price: 260, badge: "Popular" },
      { name: "Kadai Chicken", price: 260 },
      { name: "Mushroom Masala", price: 210 },
    ],
  },
  {
    id: "breads", title: "Breads",
    items: [
      { name: "Chapathi", price: 16 },
      { name: "Kerala Porotta", price: 16 },
      { name: "Kubboos", price: 13 },
      { name: "Nool Porotta", price: 22 },
      { name: "Rumali Roti", price: 22 },
      { name: "Wheat Porotta", price: 22 },
    ],
  },
  {
    id: "starters", title: "Starters",
    items: [
      { name: "Chicken Lollipop", price: 260 },
      { name: "Dragon Chicken", price: 260 },
      { name: "Honey Glazed Chicken", price: 260 },
      { name: "Chicken 65", price: 260 },
      { name: "Chicken Kondattam", price: 260 },
      { name: "Beef Pidichathu", price: 230 },
      { name: "Beef Thoran", price: 230 },
      { name: "DDF", price: 230 },
    ],
  },
  {
    id: "soups", title: "Soups",
    items: [
      { name: "Cream of Chicken", price: 90 },
      { name: "Cream of Mushroom", price: 90 },
      { name: "Hot & Sour Chicken", price: 90 },
      { name: "Hot & Sour Vegetable", price: 90 },
      { name: "Manchow Chicken", price: 90 },
      { name: "Sweet Corn Chicken", price: 90 },
    ],
  },
  {
    id: "salads", title: "Salads",
    items: [
      { name: "Farmers Salad", price: 90 },
      { name: "Toast Salad", price: 90 },
      { name: "Arabic Salad", price: 260 },
      { name: "Lettuce Salad", price: 260 },
      { name: "Russian Salad", price: 250 },
      { name: "Green Salad", price: 140 },
      { name: "Hummus", price: 200 },
      { name: "Beetroot Hummus", price: 220 },
      { name: "Baba Ganoush", price: 190 },
      { name: "Mutabal Salad", price: 220 },
      { name: "Turkish Hot Salad", price: 260 },
    ],
  },
  {
    id: "biryani", title: "Biryani",
    items: [
      { name: "Chicken Dum Biryani", price: 195 },
      { name: "Batkal Chicken Biryani", price: 225 },
      { name: "Ghee Rice", price: 80 },
    ],
  },
  {
    id: "juices", title: "Fresh Juices",
    items: [
      { name: "Watermelon", price: 70 },
      { name: "Apple", price: 140 },
      { name: "Grapes", price: 80 },
      { name: "Mango", price: 120 },
      { name: "Pineapple", price: 80 },
      { name: "Musambi", price: 100 },
      { name: "Papaya", price: 80 },
      { name: "Pomegranate", price: 140 },
      { name: "Shamam Juice", price: 80 },
      { name: "Fresh Lime", price: 40 },
      { name: "Mint Lime", price: 45 },
      { name: "Grape Lime", price: 45 },
      { name: "Pineapple Lime", price: 45 },
      { name: "ABC (Doctor Special)", price: 140 },
      { name: "Healthy Cool", price: 140 },
      { name: "Liver Cure", price: 140 },
      { name: "Raid Recovery", price: 140 },
      { name: "Weight Loss Magic", price: 140 },
    ],
  },
  {
    id: "shakes", title: "Shakes",
    items: [
      { name: "Chikku Shake", price: 120 },
      { name: "Grapes Shake", price: 120 },
      { name: "Mango Shake", price: 120 },
      { name: "Mixed Fruit Shake", price: 160 },
      { name: "Papaya Shake", price: 90 },
      { name: "Pomegranate Shake", price: 140 },
      { name: "Sharjah Shake", price: 90 },
      { name: "Butterscotch Ice Cream Shake", price: 140 },
      { name: "Chocolate Ice Cream Shake", price: 140 },
      { name: "Cream of Delights Special Shake", price: 170 },
      { name: "Fig & Honey Ice Cream Shake", price: 160 },
      { name: "Mango Ice Cream Shake", price: 140 },
      { name: "Pista Ice Cream Shake", price: 150 },
      { name: "Spanish Delight Shake", price: 150 },
      { name: "Strawberry Ice Cream Shake", price: 140 },
      { name: "Tender Coconut Ice Cream Shake", price: 160 },
      { name: "Vanilla Ice Cream Shake", price: 120 },
      { name: "Arabian Delight Shake", price: 180, badge: "Signature" },
      { name: "Brown Booster Shake", price: 160 },
      { name: "Brown Punch Shake", price: 180 },
      { name: "Coffee Delight Shake", price: 140 },
      { name: "Kittax Shake", price: 170 },
      { name: "Mississippi Mud Shake", price: 190, badge: "Popular" },
      { name: "Oreo Shake", price: 175, badge: "Bestseller" },
      { name: "Wild Sagitta Shake", price: 180 },
    ],
  },
  {
    id: "mojitos", title: "Mojitos",
    items: [
      { name: "3 Ways Qawwali Signature", price: 169, badge: "Signature" },
      { name: "Apple Fusion", price: 140 },
      { name: "Blue Caraco", price: 130 },
      { name: "Blueberry", price: 130 },
      { name: "Blue Lady", price: 130 },
      { name: "Dark Night", price: 140 },
      { name: "Ginger Mountain", price: 130 },
      { name: "Green Apple", price: 130 },
      { name: "Litchi Trigger", price: 130 },
      { name: "Mint Mojito", price: 130 },
      { name: "Passion Fruit", price: 130 },
      { name: "Pina Colada", price: 140 },
      { name: "Sunset Yellow", price: 140 },
      { name: "Virgin Mojadnia", price: 140 },
    ],
  },
  {
    id: "falooda", title: "Falooda & Ice Cream",
    items: [
      { name: "Choco Fudge Sundae", price: 150 },
      { name: "Choco Van Sundae", price: 160 },
      { name: "Coolbasket Sundae", price: 180 },
      { name: "Gudbud Sundae", price: 180 },
      { name: "Tom & Jerry Qawwali Special", price: 180, badge: "Signature" },
      { name: "Blueberry Ice Cream", price: 150 },
      { name: "Butterscotch Ice Cream", price: 140 },
      { name: "Chocolate Ice Cream", price: 100 },
      { name: "Fig & Honey Ice Cream", price: 190 },
      { name: "Mango Ice Cream", price: 130 },
      { name: "Pista Ice Cream", price: 140 },
      { name: "Spanish Delight", price: 140 },
      { name: "Strawberry", price: 100 },
      { name: "Tender Coconut Ice Cream", price: 150 },
      { name: "Tender Coconut Kulfi", price: 130 },
      { name: "Vanilla Ice Cream", price: 100 },
      { name: "Vibgyor Falooda Ice Cream", price: 260, badge: "Popular" },
      { name: "Italian Falooda", price: 220 },
      { name: "Mini Falooda", price: 100 },
      { name: "Nutty Falooda", price: 240 },
      { name: "Pista Falooda", price: 160 },
      { name: "Chocolate Falooda", price: 160 },
      { name: "Royal Falooda", price: 200 },
      { name: "Special Falooda", price: 260 },
      { name: "Couple Bite", price: 260 },
    ],
  },
  {
    id: "hot", title: "Hot Beverages",
    items: [
      { name: "Tea", price: 22 },
      { name: "Lime Tea", price: 22 },
      { name: "Mint Tea", price: 22 },
      { name: "Mint Lime Tea", price: 27 },
      { name: "Passion Fruit Tea", price: 42 },
      { name: "Black Tea", price: 15 },
      { name: "Boost", price: 32 },
      { name: "Horlicks", price: 32 },
      { name: "Coffee", price: 32 },
      { name: "Black Coffee", price: 25 },
    ],
  },
  {
    id: "family", title: "Family Meals",
    items: [
      { name: "8–10 Pieces for 4 Muttas", price: 599, badge: "Family Favourite" },
      { name: "Kizhi Al-Faham Meal", price: 1699, badge: "Signature" },
      { name: "Make It A Meal with Any Dish", price: 159 },
      { name: "Shawarma Meal", price: 299, badge: "Popular" },
      { name: "Non Vegetarian Sadya", price: 599 },
    ],
  },
];

export const formatPrice = (price: Price): string => {
  if (price === "APS") return "As Per Selection";
  if (typeof price === "number") return `₹${price}`;
  const parts: string[] = [];
  if (price.q !== undefined) parts.push(`Q ₹${price.q}`);
  if (price.h !== undefined) parts.push(`H ₹${price.h}`);
  if (price.f !== undefined) parts.push(`F ₹${price.f}`);
  return parts.join(" · ");
};
